---
- name: "Include labocbz.deploy_docker_swarm playbook"
  tags:
      - "labocbz.deploy_docker_swarm"
  vars:
    tower_env: "cicd-ubuntu-22"
  ansible.builtin.import_playbook: "../../playbook.yml"
